version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: cointrade-postgres
    environment:
      POSTGRES_DB: cointrade
      POSTGRES_USER: coinuser
      POSTGRES_PASSWORD: your_password
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  mongodb:
    image: mongo:6
    container_name: cointrade-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  backend:
    build: ./backend
    container_name: cointrade-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongodb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cointrade
      SPRING_DATASOURCE_USERNAME: coinuser
      SPRING_DATASOURCE_PASSWORD: your_password
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/cointrade
    restart: unless-stopped

volumes:
  postgres-data:
  mongo-data:
